/*
 * This file is generated by jOOQ.
 */
package trrp.lab4.dto;


import java.time.OffsetDateTime;
import java.util.List;

public class EgrulUsersDTO {

    private String         ogrn;
    private String         lastName;
    private String         firstName;
    private String         patronymic;
    private OffsetDateTime lastUpdateDate;
    private List<EgrulInfoDTO> egrulInfoDTOS;

    public EgrulUsersDTO() {}

    public EgrulUsersDTO(String ogrn, String lastName, String firstName, String patronymic, OffsetDateTime lastUpdateDate) {
        this.ogrn = ogrn;
        this.lastName = lastName;
        this.firstName = firstName;
        this.patronymic = patronymic;
        this.lastUpdateDate = lastUpdateDate;
    }

    public String getOgrn() {
        return this.ogrn;
    }

    public void setOgrn(String ogrn) {
        this.ogrn = ogrn;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getPatronymic() {
        return this.patronymic;
    }

    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }

    public OffsetDateTime getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(OffsetDateTime lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public List<EgrulInfoDTO> getEgrulInfoDTOS() {
        return egrulInfoDTOS;
    }

    public void setEgrulInfoDTOS(List<EgrulInfoDTO> egrulInfoDTOS) {
        this.egrulInfoDTOS = egrulInfoDTOS;
    }
}
